default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nikson_fishing_server_development

test:
  <<: *default
  database: nikson_fishing_server_test

production:
  primary: &primary_production
    <<: *default
    database: nikson_fishing_server_production
    username: nikson_fishing_server
    password: <%= ENV["NIKSON_FISHING_SERVER_DATABASE_PASSWORD"] %>
    host: <%= ENV["DATABASE_HOST"] %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  cache:
    <<: *primary_production
    database: nikson_fishing_server_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: nikson_fishing_server_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: nikson_fishing_server_production_cable
    migrations_paths: db/cable_migrate
