name: Codebase check
on: push

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1.221.0
        with:
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop --parallel
