name: Codebase check
on: push

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1.221.0
        with:
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop --parallel

  rspec:
    name: RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1.221.0
        with:
          bundler-cache: true

      - name: Create DB
        run: bin/rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec
